config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#message_perso'
  get 'pages/message_perso', to: "pages#message_perso"
  get 'pages/message_groupe', to: "pages#message_groupe"
  get 'pages/membre_groupe', to: "pages#membre_groupe"

  resources :groups do
    resources :registrations
    resources :conversations do
      resources :messages
      get "addlike", to: "conversations#add_like"
    end
  end
  resources :chapters
  devise_for :users
end

app/views/pages/home.html.erb
<p>Accueil</p>
<%= link_to "page 1", pages_message_perso_path, class: "btn btn-primary btn-lg" %>

app/views/pages/membre_groupe.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="panel panel-white post panel-shadow">
        <div class="banner">
          <div class="banner-content">
            <h1>Membres du groupes</h1>
            <div class="members">
              <div class="member">
                <a class="avatar-large" href="#">
                  <%= image_tag "alice.png", height: 90 %>
                </a>
                <div class="members-body">
                  <p><strong>Alice</strong></p>
                </div>
              </div>
              <div class="member">
                <a class="avatar-large" href="#">
                  <%= image_tag "isabelle.png", height: 90 %>
                </a>
                <div class="members-body">
                  <p><strong>Isabelle</strong></p>
                </div>
              </div>
              <div class="member">
                <a class="avatar-large" href="#">
                  <%= image_tag "michel.png", height: 90 %>
                </a>
                <div class="members-body">
                  <p><strong>Michel</strong></p>
                </div>
              </div>
              <div class="member">
                <a class="avatar-large" href="#">
                  <%= image_tag "sandra.png", height: 90 %>
                </a>
                <div class="members-body">
                  <p><strong>Sandra</strong></p>
                </div>
              </div>
            </div>
            <%= link_to "Rejoindre notre groupe", group_conversation_path(@group, @conversation), class: "btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/message_groupe.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="panel panel-white post panel-shadow">
        <div class="banner">
          <div class="banner-content">
            <h1>Groupe <span style="color:#cbb12b;font-weight: bold;">Alpha</span></h1>
            <div class="description_group_message">
              <p>
              Nous sommes très heureux de t’accueillir dans notre groupe.
              <br />
                Je pense sincèrement que venir pour la première fois n’est pas une expérience facile, et il y a peut-être un certain nombre de pensées qui te traversent l’esprit en ce moment. <br />
              <br />
                Tu te demande peut-être: <br />
                « Est-ce que je vais être la seule personne à ne pas être un chrétien ultra convaincu ? »
              <br /> <br />
                Tu n’es pas le seul, en fait, ce parcours est tout entier conçu pour toi, il est conçu pour des personnes qui ne vont pas à l’église. Tout le monde y est bienvenu. <br /> <br />
                Une autre question que tu te poses certainement : <br />
                « Est-ce qu’on va m’obliger à faire des choses que je n’ai pas envie de faire ? » <br />
                NON, rien ni personne ne te forcera à faire quelque chose que tu ne veux pas. <br /> <br/>

                Pour commencer, nous sommes ravis que tu sois là, et nous serions très heureux que tu participes à nos rencontres et aux échanges sur le site, parce que notre groupe suit une progression logique et tu en retireras beaucoup plus si tu le suis à chaque rencontre. Mais si tu décides de ne pas revenir, c’est entièrement ton choix : on ne t’écrira pas, on ne t’enverra pas de mail, pas de message texto, on ne te téléphonera pas. Chaque rencontre, c’est à toi de décider de venir ou non. Personne ne te courra après! <br /> <br />
              </p>
            </div>
            <%= link_to "Découvre les membres", pages_membre_groupe_path, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/message_perso.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="panel panel-white post panel-shadow">
        <div class="banner">
          <div class="banner-content">
            <h1>Bienvenue mon ami !</h1>
            <p>Sois le bienvenu sur le réseau social de notre groupe de partage biblique. Nous sommes content que tu répondes positivement à notre invitation. Je te propose d’en savoir plus dans les pages suivantes avant de nous rejoindre sur le réseau social.</p>
            <%= link_to "Découvre notre groupe", pages_message_groupe_path, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>